application: worldwidelexicon2
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: image/favicon.ico
  upload: image/favicon.ico

- url: /code
  static_dir: code
    
- url: /css
  static_dir: css

- url: /docs
  static_dir: docs
  
- url: /image
  static_dir: image

- url: /javascript
  static_dir: javascript
    
- url: .*
  script: main.py
