application: worldwidelexicon
version: 2
runtime: python
api_version: 1

handlers:
    
- url: /robots.txt
  script: admin.py

- url: /favicon.ico
  static_files: image/favicon.ico
  upload: image/favicon.ico

- url: /icon
  static_files: image/logo.png
  upload: image/logo.png

- url: /logo
  static_files: image/logo.png
  upload: image/logo.png

- url: /static
  static_dir: static

- url: /image
  static_dir: image

- url: /dermundocss
  static_dir: dermundocss

- url: /dermundocss/css
  static_dir: dermundocss/css

- url: /dermundocss/images
  static_dir: dermundocss/images
  
- url: /api
  script: home.py

- url: /batch
  script: translations.py

- url: /cache
  script: translations.py

- url: /css
  static_dir: css

- url: /doc
  script: home.py
  
- url: /admin
  script: admin.py
  secure: optional

- url: /admin/(.*)
  script: admin.py
  secure: optional

- url: /blacklist/(.*)
  script: blacklist.py
  
- url: /comments/(.*)
  script: comments.py
  secure: optional
  
- url: /cron/(.*)
  script: cron.py
  
- url: /domains/(.*)
  script: admin.py
  secure: optional

- url: /f
  script: translations.py
  
- url: /headers
  script: admin.py
  secure: optional
  
- url: /heartbeat
  script: purge.py
  secure: optional
  
- url: /hosts/auth/(.*)
  script: hosts.py
  secure: optional
  
- url: /hosts/(.*)
  script: hosts.py
  secure: optional
  
- url: /language
  script: language.py

- url: /language/(.*)
  script: language.py
  
- url: /log
  script: translations.py

- url: /lsp/(.*)
  script: lsp.py

- url: /mt/(.*)/(.*)/(.*)
  script: mt.py

- url: /mt/(.*)/(.*)
  script: mt.py

- url: /mt
  script: mt.py

- url: /ngrams
  script: translations.py
  
- url: /proxy/(.*)
  script: proxy.py
  secure: optional

- url: /purge/(.*)
  script: purge.py

- url: /p/(.*)
  script: translations.py

- url: /p
  script: translations.py
  
- url: /q
  script: translations.py

- url: /r
  script: translations.py

- url: /ratelimit
  script: ip.py

- url: /scores/(.*)
  script: scores.py
  secure: optional

- url: /selftest
  script: heartbeat.py
  
- url: /setup
  script: admin.py
  secure: always
  
- url: /share
  script: search.py
  secure: optional
  
- url: /sidebar
  script: firefox.py
  secure: optional

- url: /spam
  script: translations.py

- url: /status
  script: admin.py
  
- url: /stats/scores
  script: scores.py
  secure: optional
  
- url: /stream
  script: main.py
  
- url: /submit
  script: translations.py
  secure: optional
  
- url: /t/(.*)/(.*)/(.*)
  script: translations.py
  
- url: /t/(.*)/(.*)
  script: translations.py
  
- url: /t
  script: translations.py

- url: /translate/(.*)
  script: translate.py

- url: /translate
  script: translate.py

- url: /transense/(.*)
  script: transense.py

- url: /transense
  script: transense.py

- url: /u
  script: translations.py
  
- url: /unicode
  script: translations.py
  
- url: /users/(.*)
  script: users.py
  secure: optional

- url: /(.*)/(.*)/(.*)
  script: main.py
  secure: optional
  
- url: /(.*)/(.*)
  script: main.py
  secure: optional
  
- url: /(.*)
  script: main.py
  secure: optional

- url: /
  script: main.py
  secure: optional

- url: .*
  script: main.py
  secure: optional
