application: wwlapi
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
    
- url: /favicon.ico
  static_files: dermundoimage/favicon.ico
  upload: dermundoimage/favicon.ico
  
- url: /admin
  script: admin.py
  
- url: /admin/(.*)
  script: admin.py
    
- url: /example
  script: example.py
  
- url: /secret1940
  script: home.py
  
- url: /beta/register
  script: home.py
  
- url: /dermundocss
  static_dir: dermundocss

- url: /dermundocss/css
  static_dir: dermundocss/css
  
- url: /dermundoimage
  static_dir: dermundoimage
  
- url: /groups/(.*)
  script: home.py
  
- url: /dermundo/(.*)
  script: home.py
  
- url: /lsp/worker
  script: lsp.py
  
- url: /q
  script: home.py
  
- url: /u
  script: home.py

- url: /translate/project
  script: home.py
  
- url: /language
  script: language.py
  
- url: /profile/(.*)
  script: home.py
  
- url: /robots.txt
  script: home.py
  
- url: /stream
  script: home.py
  
- url: /sidebar
  script: home.py
  
- url: /submit
  script: home.py
  
- url: /help/firefox
  script: home.py
  
- url: /x(.*)/(.*)
  script: home.py
  
- url: /x(.*)
  script: home.py
  
- url: /wwl/deletemessage/(.*)
  script: home.py
  
- url: /wwl/email
  script: email.py
  
- url: /wwl/crawler
  script: crawler.py
  
- url: /wwl/localize
  script: ui.py
  
- url: /wwl/meta/(.*)
  script: home.py
  
- url: /wwl/mt/(.*)
  script: mt.py

- url: /wwl/mt
  script: mt.py
  
- url: /wwl/geo
  script: relay.py
  
- url: /wwl/meta/translation
  script: home.py
  
- url: /wwl/scores/vote
  script: home.py
  
- url: /wwl/language
  script: relay.py
  
- url: /wwl/domain
  script: relay.py
  
- url: /wwl/im/(.*)
  script: relay.py
  
- url: /wwl/(.*)
  script: home.py
  
- url: /users/logout
  script: relay.py
  
- url: /
  script: home.py

- url: /.*
  script: mirror.py
  secure: optional