application: wwlapi
version: secureable
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
  
- url: /dermundocss
  static_dir: dermundocss

- url: /dermundocss/css
  static_dir: dermundocss/css
  
- url: /dermundoimage
  static_dir: dermundoimage
  
- url: /translate/view
  script: translate.py
  
- url: /translate/project
  script: translate.py
  
- url: /language
  script: language.py
  
- url: /sidebar
  script: translate.py
  
- url: /help/firefox
  script: translate.py
  
- url: /x(.*)/(.*)
  script: translate.py
  
- url: /x(.*)
  script: translate.py

- url: /wwl/mt
  script: mt.py
  
- url: /wwl/geo
  script: relay.py

- url: /wwl/u
  script: relay.py
  
- url: /wwl/t
  script: relay.py

- url: /wwl/submit
  script: translate.py
  
- url: /wwl/scores/vote
  script: relay.py
  
- url: /wwl/language
  script: relay.py
  
- url: /wwl/domain
  script: relay.py
  
- url: /wwl/im/(.*)
  script: relay.py
  
- url: /wwl/userstats
  script: translate.py
  
- url: /
  script: translate.py

- url: /.*
  script: mirror.py
  secure: optional