application: speaklikeim
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

handlers:

- url: /css
  static_dir: css

- url: /docs
  static_dir: docs

- url: /javascript
  static_dir: javascript

- url: /liveperson
  static_dir: liveperson

- url: /liveperson/images
  static_dir: liveperson/images

- url: /realtime/(.*)
  script: realtime.py

- url: /_ah/xmpp/(.*)/(.*)
  script: realtime.py

- url: .*
  script: realtime.py
