<?php
// $Id: wwlex.install

/**
* Implementation of hook_install()
*/
function wwlex_install() {
  // Set the module weight so it can override other modules.
  //db_query("UPDATE {system} SET weight = 99 WHERE name = 'wwlex'");
}

/**
* Implementation of hook_uninstall()
*/
function wwlex_uninstall() {
  // Remove the module from the system table
  //db_query("DELETE FROM {system} WHERE name = 'wwlex'");
}